# Generated by Django 5.1.1 on 2024-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="stuname",
            field=models.TextField(),
        ),
    ]
