# Generated by Django 5.1.1 on 2024-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_stuname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='stuname',
            new_name='uname',
        ),
    ]
