# Generated by Django 5.1.1 on 2024-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_rename_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(default='non', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
