# Generated by Django 5.1.1 on 2024-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_dob_customuser_name_customuser_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('fetures', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(),
        ),
    ]
