# Generated by Django 5.1.1 on 2024-09-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plan_alter_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='fetures',
            new_name='features',
        ),
    ]
