# Generated by Django 5.1.1 on 2024-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_fetures_plan_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uname',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='non', max_length=128),
        ),
    ]
