# Generated by Django 5.1.1 on 2024-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_planname_customuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
