# Generated by Django 5.1.1 on 2024-09-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='price',
        ),
    ]
